version: '3.7'

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: registry.gitlab.com/khanhlee99/shopeeclone:client
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - webappnetwork

networks:
    webappnetwork:
        driver: bridge