version: '3.7'

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: shopee_front/react:v1
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - webappnetwork

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./Container/Backend/Dockerfile
  #   image: itree_back/node:v1
  #   volumes:
  #     - ./volumes/uploads:/api/uploads
  #   ports:
  #     - '9000:9000'
  #   restart: unless-stopped
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - webappnetwork

  # nginx:
    # build:
    #   context: .
    #   dockerfile: ./Container/Nginx/Dockerfile
    # image: itree_nginx/nginx:v1
    # volumes:
    #   - ./volumes/nginx:/etc/nginx/templates
    # ports:
    #   - '80:80'
    # restart: unless-stopped
    # depends_on:
    #   - client
    #   - api
    # networks:
    #   - webappnetwork

  # mongodb:
  #   image: mongo
  #   volumes:
  #     - ./volumes/data/db:/data/db
  #   restart: unless-stopped
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - webappnetwork

networks:
    webappnetwork:
        driver: bridge

# volumes:
#   data: