name: Node.js CI

on:
  push:
    branches: ['main']
  # pull_request:
  #   branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'yarn'
      - run: echo  The tags are ${{ github.event }}

      #     yarn install
      #     yarn run build
      #     yarn test --test-timeout=40000

      # - name: Deploy with gh-pages
      #   # if: github.event.push
      #   run: |
      #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
